### PR TITLE
main <- develop: 파이어베이스 서버 변경

### PR DESCRIPTION
**Pull request by hamfan524**
[💄Design: PostView 이미지 Modifier 변경](https://github.com/4T2F/PADO/commit/ac6f602637e92001c8289bcb6eee74eda24782d8)

@[Hsungjin](https://github.com/4T2F/PADO/commits?author=Hsungjin)
Hsungjin committed 5 days ago
[Merge branch 'develop' into feature/SurfingView](https://github.com/4T2F/PADO/commit/28826cfd90cabe1440b6c1035e67976c446b148f)

@[Hsungjin](https://github.com/4T2F/PADO/commits?author=Hsungjin)
Hsungjin committed 5 days ago
Commits on Jan 25, 2024
[Merge pull request](https://github.com/4T2F/PADO/commit/c91b96dbaf7dd55bdb4799f6b9c8da655f74b8fb) https://github.com/4T2F/PADO/pull/81 [from 4T2F/main](https://github.com/4T2F/PADO/commit/c91b96dbaf7dd55bdb4799f6b9c8da655f74b8fb) 

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[Merge branch 'develop' into feature/SurfingView](https://github.com/4T2F/PADO/commit/7f5a47f84fa5f464ff2a6bdee3e613e6ef4b9a5e)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[🌊 Feat: 오늘 파도 스크롤링 추가](https://github.com/4T2F/PADO/commit/7cd3da4ed73f34bbac74a041481bbd34ee7608b2)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[🌊 Feat: 그래디언트 추가](https://github.com/4T2F/PADO/commit/7e1ddb8208a144ba0c238853cdc20b702fc80248)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[🌊 Feat: SurfingViewModel 구현](https://github.com/4T2F/PADO/commit/03c673a5df2597faf8233e1f6757325fabe061ce)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[🩹 Refactor: SurfingView 파일 구조 변경](https://github.com/4T2F/PADO/commit/a4e846bc17d85957ec385364847d31ecc95c3555)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[🐞 Fix: 스플래시뷰 한 번씩 안넘어가는 오류 수정](https://github.com/4T2F/PADO/commit/742f0e88dc931c12a97155e62a70bfed0e3d40bd)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[🩹 Refactor : SurfingView에 있는 함수 뷰모델로 이동](https://github.com/4T2F/PADO/commit/5112b0cbeb6c53f97a6b1ccdb1bc571ae2a11e2f)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
Commits on Jan 26, 2024
[🌊 Feat: Setting에서 정보 변경 기능 설계](https://github.com/4T2F/PADO/commit/e95baca07326f87a14285994edb58a274bdbc507) 

@[Hsungjin](https://github.com/4T2F/PADO/commits?author=Hsungjin)
Hsungjin committed 3 days ago
[Merge pull request](https://github.com/4T2F/PADO/commit/2e5cfe812656fc673cfdeb376537a467d306e83c) https://github.com/4T2F/PADO/pull/83 [from 4T2F/feature/Firebase](https://github.com/4T2F/PADO/commit/2e5cfe812656fc673cfdeb376537a467d306e83c) 

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[Merge branch 'develop' into feature/SurfingView](https://github.com/4T2F/PADO/commit/667b00b0f4e3978d707b57ef034bf0bf31a3e741)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[Merge branch 'develop' into feature/TodayPado](https://github.com/4T2F/PADO/commit/7348268e44c901a8bb2ff810ba22ada5196bd322)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[🐞 Fix: TodayView 수정](https://github.com/4T2F/PADO/commit/59099413448ca2fd37f3c6754e9fba7c7771f72c)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[Merge pull request](https://github.com/4T2F/PADO/commit/4087466e17a14fbaa121e1b2d522395da0119695) https://github.com/4T2F/PADO/pull/85 [from 4T2F/feature/TodayPado](https://github.com/4T2F/PADO/commit/4087466e17a14fbaa121e1b2d522395da0119695) 

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[Merge branch 'develop' into feature/SurfingView](https://github.com/4T2F/PADO/commit/c5b1baf71f1b1dac93feb48699f6578065ea9994)

@[kmh5038](https://github.com/4T2F/PADO/commits?author=kmh5038)
kmh5038 committed 3 days ago
[Merge pull request](https://github.com/4T2F/PADO/commit/1b1882e130f405d2abdaac273d131449c986564c) https://github.com/4T2F/PADO/pull/86 [from 4T2F/feature/SurfingView](https://github.com/4T2F/PADO/commit/1b1882e130f405d2abdaac273d131449c986564c) 

@[kmh5038](https://github.com/4T2F/PADO/commits?author=kmh5038)
kmh5038 committed 3 days ago
[🌊 Feat: profile 변경 로직 수정](https://github.com/4T2F/PADO/commit/0b025a643e2c757c4cc89758be1fe26a0d499f6a)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[Merge branch 'develop' into feature/Firebase](https://github.com/4T2F/PADO/commit/39dd65cb83fa665284f2304a4715757d0cdf7920)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[🐞 Fix: 버전 충돌 해결](https://github.com/4T2F/PADO/commit/9f6291bc99f36fdf12be382f6d0884adfd9a60e6)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[Merge pull request](https://github.com/4T2F/PADO/commit/35bbcf2e0bc8ac2ef81460e25e46849abeeeef55) https://github.com/4T2F/PADO/pull/87 [from 4T2F/feature/Firebase](https://github.com/4T2F/PADO/commit/35bbcf2e0bc8ac2ef81460e25e46849abeeeef55) 

@[kmh5038](https://github.com/4T2F/PADO/commits?author=kmh5038)
kmh5038 committed 3 days ago
[🌊 Feat: 프로필 수정 로직 변경](https://github.com/4T2F/PADO/commit/bf7ca968466d837e6dcf261639a80726ef5f6bbc) 

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[🐞 Fix: 로그인 로직 작은 오류 수정](https://github.com/4T2F/PADO/commit/a0878ea059859a8724ff1b2ee5614bcb282a3558)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 3 days ago
[Merge pull request](https://github.com/4T2F/PADO/commit/8656a7411cd2647f0a26c140fed894ed37bd10d5) https://github.com/4T2F/PADO/pull/88 [from 4T2F/feature/SurfingView](https://github.com/4T2F/PADO/commit/8656a7411cd2647f0a26c140fed894ed37bd10d5) 

@[kmh5038](https://github.com/4T2F/PADO/commits?author=kmh5038)
kmh5038 committed 3 days ago
[🌊 Feat: MainView 모델링 및 로직 수정](https://github.com/4T2F/PADO/commit/f492b83dba9bc225ee68cecd12a821b1b2a93f58) https://github.com/4T2F/PADO/issues/89

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[🩹 Refactor: 파일 이름 수정](https://github.com/4T2F/PADO/commit/d1a39ed90e972fc3736bd222a16b4aa4d922ff1c) 

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[🌊 Feat: 항상 스토리셀의 제일 첫사진이 나오게 변경](https://github.com/4T2F/PADO/commit/427ee50107bd560e26b9cd604872013583dbe37a)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 3 days ago
[Merge pull request](https://github.com/4T2F/PADO/commit/26a8cebda89b64a7e0a94a6e52f00cc146b3bea5) https://github.com/4T2F/PADO/pull/90 [from 4T2F/feature/MainView](https://github.com/4T2F/PADO/commit/26a8cebda89b64a7e0a94a6e52f00cc146b3bea5)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 2 days ago
[🩹 Refactor: 스토리지 관련 함수 전역 클래스 선언](https://github.com/4T2F/PADO/commit/b66fb9bdc4700b6ca253b41f8f5456c7e509e6bc) 

@[Hsungjin](https://github.com/4T2F/PADO/commits?author=Hsungjin)
Hsungjin committed 2 days ago
[Merge branch 'develop' into feature/Firebase](https://github.com/4T2F/PADO/commit/44f6dbe0562b163dae2893dc389f9a6c1f7819cc)

@[Hsungjin](https://github.com/4T2F/PADO/commits?author=Hsungjin)
Hsungjin committed 2 days ago
Commits on Jan 27, 2024
[🌊 Feat: 파이어베이스에서 사진 불러오는 기능 구현](https://github.com/4T2F/PADO/commit/b185247e5f6aacda89568da042524d8028b22aee)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 19 hours ago
[🌊 Feat: 파이어베이스에서 사진 불러오는 기능 구현](https://github.com/4T2F/PADO/commit/4575585745ca4c0c01a225f4b66e73f7cf2a77fe)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 19 hours ago
[Merge pull request](https://github.com/4T2F/PADO/commit/4c59d1ca78db470739fd89a1ebcb90c1f62a120a) https://github.com/4T2F/PADO/pull/91 [from 4T2F/feature/Firebase](https://github.com/4T2F/PADO/commit/4c59d1ca78db470739fd89a1ebcb90c1f62a120a) 

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 19 hours ago
[Merge branch 'develop' into feature/MainView](https://github.com/4T2F/PADO/commit/482d154f67e91feb7e5cc872b7cd1d02427d1049)

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 19 hours ago
[Merge pull request](https://github.com/4T2F/PADO/commit/8e9ebcb869f0b490efd292082e07026456edc245) https://github.com/4T2F/PADO/pull/92 [from 4T2F/feature/MainView](https://github.com/4T2F/PADO/commit/8e9ebcb869f0b490efd292082e07026456edc245) 

@[Hminchae](https://github.com/4T2F/PADO/commits?author=Hminchae)
Hminchae committed 19 hours ago
Commits on Jan 28, 2024
[🌊 Feat: asyncImage -> KingFisher 변경](https://github.com/4T2F/PADO/commit/3e89540b0c42ba58f9586c1f02c2fc6e1bd7c0dc)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 18 hours ago
[Merge pull request](https://github.com/4T2F/PADO/commit/638b3caf82596ad6060e448a2e47790c52cd45c5) https://github.com/4T2F/PADO/pull/93 [from 4T2F/feature/MainView](https://github.com/4T2F/PADO/commit/638b3caf82596ad6060e448a2e47790c52cd45c5) 

@[kangciu](https://github.com/4T2F/PADO/commits?author=kangciu)
kangciu committed 17 hours ago
[🗑️ Remove: GoogleService-Info 삭제, 키 변경](https://github.com/4T2F/PADO/commit/d673dabb69cb7c8643b73ad4e73d0517a9b8cfac) 

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 15 hours ago
[🐞 Fix: storage 복구](https://github.com/4T2F/PADO/commit/e917908ff650f40ac4939e26080b75d65f19a0c2)

@[hamfan524](https://github.com/4T2F/PADO/commits?author=hamfan524)
hamfan524 committed 12 minutes ago

### CODE REVIEW

**Review by Hminchae — APPROVED** [review]
멋있다 파도!

**Review by kmh5038 — APPROVED** [review]
전설의 시작

**Review by kangciu — APPROVED** [review]
멘탈좋은 청년

**Review by Hsungjin — APPROVED** [review]
다시 써내려가는 파도

**Pull request merged**
